# Idea behind matrix is that you can run the same job with different configuration
# for example different runner or different node veriosns or any other value you might be interested in changing
name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12,14,16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with: 
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Build Project
      run: npm build


